const productIds = ["ubkfmdjxyzlbgkrotcepvswaqx", "uikfmdkuyzlbgerotcepvswaqh", "uikfmdpxyzlbgnrotcepvswoeh", "ikfmdjxyzlbgnrotqepvswyqh", "qgkfmdjxyzlbgnmotcepvswaqh", "uikfmdjxyzqbgnrytcepvsbaqh", "uikfmdjxyzibgprotcecvswaqh", "uikfmajxyzlcgnrojcepvswaqh", "uvkfsdjxyzlbgnrotcepvjwaqh", "uikfmdjxfzlbggrotcepvswawh", "uikfmhjxyzlbgnuotcepvjwaqh", "uikfmdjxyzlbuzcotcepvswaqh", "uikfmdwxyzlbgnrotcepvfwamh", "uikfmdexyzlbgnroecepvswhqh", "uikfmdjuyzlbgnrotcqpvswafh", "uikfddjxyzvbgnrotceppswaqh", "yikfwdjxyzlbgnrotcepvswagh", "uiktmdjxyzlbgnrotceposwajh", "uikfmdsxyzlbgnroteetvswaqh", "uikfpdjxyzlbgnroncepvswuqh", "uikfmtjxyzlbgurotcepvswaoh", "eikfmdjxyjlbgnrotcepyswaqh", "uikfkdjxyzlbgnrotcepvszaqv", "uikfrdjxtwlbgnrotcepvswaqh", "uikfmdjxyzlbgnrotpepwswahh", "kikfmdjxyzlbgnkotcepvswqqh", "uikfkduxyzlbgnrotcepvswafh", "uikfxhjxyzlbgnrotcegvswaqh", "uikfmdjxyzlmgnrotcenvawaqh", "uzkfmddxyzlbgnrltcepvswaqh",
"uikfmdjxyzlbgnrobcepisqaqh", "uijfmdjxyzlbgnrotcexvrwaqh", "uiwjmdjxyzlbgnrotceprswaqh", "uhkqmdjxwzlbgnrotcepvswaqh", "uiktmsjxyzwbgnrotcepvswaqh", "uikfmdjxyztbgnqotcepvswcqh", "uibfmdjxyzlbgnroqcepvswaqx", "uwkfmdjxyxlbgnrotcfpvswaqh", "uikumdjxyzlbgnrstceposwaqh", "uikfzdjxyznhgnrotcepvswaqh", "uikuydjxyzlbgnrotqepvswaqh", "uikfmdqxyzlbgnrotfefvswaqh", "yikfmdjxyzlbrnrqtcepvswaqh", "uiifmdjxyzlbenrotcfpvswaqh", "uxkjmdjxyzlbgnrotcmpvswaqh", "uikgmdjxyzlbgnrotceovlwaqh", "uikfmdjxyzvbgzrotcenvswaqh", "uiufmdjxyzlbgnrotceposwazh", "uiafmdjxyzlignmotcepvswaqh", "uikfmdjxyzwbgnsotlepvswaqh", "uikjmdjvyzlbgnrotcenvswaqh", "uikfmdjxyzlbonroteepvswaqi", "uikfmdjxyzldgnroxcepviwaqh", "uikvmdjxyzlbgdrotrepvswaqh", "uikfmdjyyzwbgnrotcepvzwaqh", "uikfmdjxyzzbnnvotcepvswaqh", "uikomdjxyzlbgnrotcepvuwhqh", "uikfmmjxyzbbgnrotcepvswayh", "uikfmdjfezlbgprotcepvswaqh", "uzkfmojxmzlbgnrotcepvswaqh",
"uipfmdjxyzlbgnrotceyuswaqh", "uikfmdjxyzlkgnmotcepvswadh", "uikfmdjxyzlbgnuctcbpvswaqh", "uikfqdjxyzlbogrotcepvswaqh", "uikfmdjxyzlfynrotcepvswash", "uikfmdjxizzmgnrotcepvswaqh", "uhkfmdjxyzlbhnrotcenvswaqh", "uipfmdjxyzlbgorotcepfswaqh", "uikfmdjxyznbgnrotcepvswfah", "uikfmujxyzlbgnrotnepvssaqh", "uikfmdjxyzlxgnrotcepvsrwqh", "uikfmdjxszlbgnrottvpvswaqh", "umkfmdskyzlbgnrotcepvswaqh", "uikfmdjxyzlbgorotcwpzswaqh", "uikfmdhxyzzbgnzotcepvswaqh", "jikfmdjxyzlbgnrotcepveyaqh", "uirfmdlxyzlbgnjotcepvswaqh", "uikfmdjxyzlbgnrorxepvswazh", "uikfmdjxyzltgnrotcepvsxaqi", "uikfmdjxyzlbxlrotcepkswaqh", "uvkfmdjxyzlbgnrotcopvswxqh", "uxkfmdjxkzlbgnrotcepvswqqh", "uikfmdjxyzlbqnrotcepvhwrqh", "uikfmdjxyzlvgnrolcepvswrqh", "urkfmdixyzlbgnrotcepvsjaqh", "uikfmdjxymlbsnrotcepvswcqh", "uikfmdjxyilbgnrotcepvcwzqh", "uikfadjxlzlbgnrotcepvswaql", "uikfmdjxuzlbgdrotcgpvswaqh", "yikfmdgxyzlbgnrotcepvswarh",
"uikfmdjxyzlbgorotcepcswaqv", "uikkmdjxyzlbvnrotcepvvwaqh", "uwzfmdjxyxlbgnrotcfpvswaqh", "uikfmdjxyztbgnrotcrtvswaqh", "uiufmdjxyzhbgnrotcupvswaqh", "uikfzdjcyzlbgnrotcfpvswaqh", "uipfmdjxyzlbgnrotavpvswaqh", "uikfmajxyzlbgnrotcepbsxaqh", "uikfmdjfyzlbgnrotbepvswmqh", "gikkmdjxyzlbgnrptcepvswaqh", "uikfmdjxqvlbgnrotsepvswaqh", "fikfmdjxyzlbgnrotcegvswoqh", "idkfmdjxyzlbgnrotcepwswaqh", "uikfmdqxyzlbmnrobcepvswaqh", "uikfmdjxyzpbgnroicepvsyaqh", "uikfmkoxyzlbgnrotcgpvswaqh", "unkfmdjxyzlbpnrolcepvswaqh", "uikfmdjmyzlbgfrotcupvswaqh", "ujkfmdjxynlbgnroteepvswaqh", "uikfmljxyzlbgnaotcepvsiaqh", "uikfmdjdyzlbgnrotcepvtwaqd", "uikfmdjxyzlbgnyotcepimwaqh", "uikfmdjxyzfbjnrotcepvxwaqh", "eiwfmdjxyzlbgnrdtcepvswaqh", "umkhmdjxyzlbgnrotceivswaqh", "uikfmdjxyzlbgnrotcwpvswneh", "uckfmdjxyzlbknrotcepvswauh", "uiofmdjoyzlbgnrbtcepvswaqh", "uikfmdbxyzlbgnrotcepaslaqh", "uimfmdjxyalbgnrotcepvswaxh",
"uqkfmdjxyzlbwnrotcepmswaqh", "uiyfmdjxyzlbgnrotcepvswxuh", "uikfmdjxyzlbgmrotgepvswamh", "uikfmdjxyqlbgarozcepvswaqh", "uikfmdjxyzabanpotcepvswaqh", "uikfmdjgyzlbsnrotcepvswaqj", "uikfmdjxyzlbwnrottepvsvaqh", "uikfmdjxyzlbbnrotcepvofaqh", "uikfudjxyzlbgnustcepvswaqh", "cskfmqjxyzlbgnrotcepvswaqh", "uiwfmddxyzlbgnrotccpvswaqh", "eikpmdjxyzlbgnrotcesvswaqh", "uikfmdzxyzlngnrrtcepvswaqh", "uikfmdjxyzlbgnrotcepaswtph", "uirfmdjxyzlbgnrotcepvswsqe", "uikjmdjxqzlbgirotcepvswaqh", "uikfmdjxsllbknrotcepvswaqh", "uikfmdjxyqlbgcrotcepvswaqu", "uikfmdjsymlbgnrotcebvswaqh", "uikfmdjxezlbgnroccepviwaqh", "uikfmdjiyzjbgnrotcepvswarh", "uqkfmdjxyzmbgnrotcepvslaqh", "unkfmdjxyzlbinrotceplswaqh", "uikfmdjxyzpbgnrjtcedvswaqh", "uicfmdjxyzlbgrrotcepvswamh", "ukknmdjxyzlbgnqotcepvswaqh", "uikfudjxyzlbdnrztcepvswaqh", "uikfmdjxyzlbgnrozcepvswawk", "uikfmduxyzsbgnrotcepvswauh", "uikfmdjxyzljbnrotcenvswaqh",
"uukfmdjxyzlbgnrotcckvswaqh", "uilfldjxyzlbgnrotcdpvswaqh", "uckfmdjxyvybgnrotcepvswaqh", "qikfmdjxyglbgnrotcepvrwaqh", "uikfmhjxyzltgnrotcepvswbqh", "uikfmdjxipabgnrotcepvswaqh", "uikfmdjxyzlbgnrotceovswanl", "uikfmdjxyzlbgirotcapvswahh", "uikfucjxyflbgnrotcepvswaqh", "pikfmdjxyzpbgnrotcepvswaeh", "uikfmdjiyylbgnrotcervswaqh", "uikfmdjgyzlbgnrotcaevswaqh", "uikvmdjxyzlbunrotcepvswarh", "uikfadjuyzpbgnrotcepvswaqh", "uikfmdjxyzlbgnrotcepsawaqj", "eikfmdjxyflbgnrotcepvswaeh", "uisfmdaxyzlbgnrotcepvswlqh", "vikfmdjxyzlzgnrotcepvswanh", "ukkfmdoxyzlbgnrotcewvswaqh", "uikfmdhxyzlbgnrotcrpvbwaqh", "uhkfmdjwezlbgnrotcepvswaqh", "uikfddjxyzlbgnroteepvpwaqh", "uikfmdjxczlbgncotiepvswaqh", "uikfvdjxyzlbgnrotcnpvsaaqh", "uikfmdjxyzlbgnritcepvlwmqh", "uikfmdjxczlcgnrotcecvswaqh", "mikfmdjxyzlbgnrotcepvswasi", "uifvmdjxyzlbgnrotpepvswaqh", "uikzmdjxyzlbgnrotrepvswaqs", "uikfmqjqyzlbunrotcepvswaqh",
"uikfpdyxyzlbgnrotcepvswagh", "uikfmdjxyzobgnrotrlpvswaqh", "zisdmdjxyzlbgnrotcepvswaqh", "uikfmdjxyzlbgnlotiesvswaqh", "uikfddixyzlbgnroucepvswaqh", "uijfmdrxyzlbgnrotoepvswaqh", "uikfmdcxbzlbgnrotcepvpwaqh", "uikfmdjxxzlbfnrotcecvswaqh", "upkfmdjxyzmtgnrotcepvswaqh", "uikfmdrxyzlbgnrjtcepvswaqp", "uizfmdjxyzlbsnrotcepviwaqh", "uidfmdjxyslbgnrotcxpvswaqh", "uikfmdjxyzlbgnrovyepvsdaqh", "uiafmdjxyzlbgnrxtcepvsdaqh", "ugkfmdjxyzlbgnrodcepvswawh", "pikfmtjxyzhbgnrotcepvswaqh", "uikfmdjxyzlfgnvotcepvswtqh", "uikbmdjxyzlbgerotcepvswaqm", "uikfmdjxyhlbdnrotcepvswaqy", "uikfgdjxyzlbgnhotcepvswdqh", "uikfmdpxyzlbgnrotcepvscanh", "uikfmdjxyzsbgnretcepvswaqn", "uikfddjxyzlrgnrotcepvsbaqh", "uikfmdjxyzlbgnrotcqnrswaqh", "uhkfmejxyzlbgnrotvepvswaqh", "uikimdjxyzlngnrotceprswaqh", "uikfmdjxyzwbunrotiepvswaqh", "rikfmdjxyzlbgnrotcypvssaqh", "uikfmdjxyzlbdnrotcrpvswsqh", "uekfmdjxkzlbznrotcepvswaqh",
"uikfmdjxyglbgvrotcepvswaqv", "uikfmcjxyzlbgnrotmeovswaqh", "uikfmdjxyznbgnrozcepvswaqm", "uikfmdjxyzlbdnrotcepdsyaqh", "umkfmdjxfzlbgnrotiepvswaqh", "uitfmdjxyzvbcnrotcepvswaqh", "uikfmdjqyzlbgnrvtcepvlwaqh", "uikfmdjxyzkbworotcepvswaqh", "uikfmdzxyzlbwnrotcypvswaqh", "uikfmdjxyklbgnrftyepvswaqh", "uinfmsjxyzlbgnrotcepsswaqh", "xisfmdjxymlbgnrotcepvswaqh", "uikfmdjxjzlbgnropcepvswaqv", "uikfmdjxyalegyrotcepvswaqh", "uikfydjxyzlbgnrotcekvswtqh", "uikwmojxyzlbgnromcepvswaqh", "uikdmdjayzlbgnrotcepvswzqh", "uikfmdjxyzlmvnrotctpvswaqh", "uikfmbjxyzlbgnrotceptsweqh", "yvkfmdjxyzlbgqrotcepvswaqh", "uikomdjxfxlbgnrotcepvswaqh", "uikfmdjxczlbgnroocepgswaqh", "uikemdjxizlbgnrotcegvswaqh", "uikdmdjxyzlbgwrotceprswaqh", "tiyfmdjfyzlbgnrotcepvswaqh", "tmkfmdjxyzlbgirotcepvswaqh", "uikfmdjxyzebgnzotcepqswaqh", "uikfmljxyzlbgnrwtcepvswaeh", "uikfmojxyzlbgnrotcepbswwqh", "uikfmdjxyzlbgsrotcewvswwqh",
"uikfmdjhyzlbgdrogcepvswaqh", "uikfmvjxyzlbrnrltcepvswaqh", "jikfmdjxyzlbgnrotcepvgcaqh", "uikhtdjxyzlbgnrotcepvswarh", "uikfmdjxyezbgnritcepvswaqh", "uikfwdjxyzlbgnrotzepvsnaqh", "uikfmdjxqylbgnrobcepvswaqh", "zikzmdjxyzlbgnrhtcepvswaqh", "uiksmzjxyzlbgnrftcepvswaqh", "uikfmdjxuzlbgnrotcepvsvaqc"]


const findProduct = () => {
    for (const productId1 of productIds) { //iterate products Ids
        let array1 = productId1.split("") //split into an array
        for (const productId2 of productIds) { //iterate product Ids again
            let array2 = productId2.split("") // split into an array again
            let count = 0 //establish count
            for (let i=0; i<array1.length; i++){ //loop for the length of the array
                if(array1[i] !== array2[i]){
                    count++ //bump up the count when the letters don't match
                }
            }
            if(count===1){ //if there is only 1 letter that doesn't match
                return productId1 //return the thing
            }
        }
    }
}

console.log(findProduct())